
title: "Uptec – Cloud done differently"
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://averkinderen.github.io/uptec.github.io" # the base hostname & protocol for your site, e.g. http://example.com
phone_number: "+61450590633"
email: "info@uptec.io"
company_name: "Uptec Pty Ltd"
site_logo_one: "/assets/img/Logo-transparant.png"
site_logo_two: "/assets/images/logo_3.png"
site_logo_three: "/assets/images/logo_2.png"
site_name: "Uptec"

page_banner_image: "/assets/img/bg/breadcrumb_bg.png"

facebook_url: 
twitter_url: "https://twitter.com/uptecau"
behance_url: 
youtube_url: 
instagram_url: 

mailchimp_url: "https://uptec.us2.list-manage.com/subscribe?u=c2799a11ac7bed585a5973cb9&id=dfa23c9645"

permalink: "/:title"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num"

feed:
  collections:
    posts:
      path: "/index.xml"
